#!/usr/bin/env python
from socket import * 

if __name__ == '__main__':
    target = input('Enter IP to scan: ')
    targetIP = gethostbyname(target)
    print ('Starting scan on host ', targetIP)

    #scan Ports
    for i in range(1, 9000):
        s = socket(AF_INET, SOCK_STREAM)

        result = s.connect_ex((targetIP, i))

        if(result == 0) :
            print ('Port %d: OPEN' % (i,))
        s.close()